### ISSUE TITLE
Ревью #1

### ISSUE THREAD

**Issue by ShkiTTer** [delet-dis/visual-novel#1]
1. Ты используешь `SharedPreferences` в каждой активити. Почему бы не вынести всю работы с ними в отдельный класс вместо копипасты?

2. Такие вещи, как имена полей в хранилище или в интенте нужно выносить в константы. Иначе опечатаешь точно, если их будет не 2-3 в паре мест, а гораздо больше.
https://github.com/delet-dis/visual-novel/blob/0a7792f344653943024f9c8a7464874669fd950b/app/src/main/java/com/delet_dis/vusialnovel/MainActivity.kt#L19-L24

3. Не бойся разделять код на блоки пустой строкой. Читать такое как-то больно.
https://github.com/delet-dis/visual-novel/blob/0a7792f344653943024f9c8a7464874669fd950b/app/src/main/java/com/delet_dis/vusialnovel/AcquaintanceActivity.kt#L14-L24

4. Здесь явно нужна проверка. Даже сама студия об этом предупреждает. 
https://github.com/delet-dis/visual-novel/blob/0a7792f344653943024f9c8a7464874669fd950b/app/src/main/java/com/delet_dis/vusialnovel/SceneActivity.kt#L23

5. Здесь студия предупреждает, что из метода может прилететь nullable значение, а ты проигнорировал проверку.
https://github.com/delet-dis/visual-novel/blob/0a7792f344653943024f9c8a7464874669fd950b/app/src/main/java/com/delet_dis/vusialnovel/SceneActivity.kt#L25

6. Переменная `processingScene` используется только внутри цикла. Вопрос, зачем тогда она вне?
https://github.com/delet-dis/visual-novel/blob/0a7792f344653943024f9c8a7464874669fd950b/app/src/main/java/com/delet_dis/vusialnovel/SceneActivity.kt#L27

7. Здесь получилось дублирование логики. Ты дважды устанавливаешь текст в текстовое поле, причем во всех случаях кроме одного один и тот же
https://github.com/delet-dis/visual-novel/blob/0a7792f344653943024f9c8a7464874669fd950b/app/src/main/java/com/delet_dis/vusialnovel/SceneActivity.kt#L43-L50

8. Я бы вынес создание кнопки в отдельный метод. А то твой onCreate прям распух уже. А вообще кнопку сверстать в отдельном XML-файле и создавать с помощью `LayoutInflater`. Тогда не придется прописывать все свойства через код.
https://github.com/delet-dis/visual-novel/blob/0a7792f344653943024f9c8a7464874669fd950b/app/src/main/java/com/delet_dis/vusialnovel/SceneActivity.kt#L60-L80

9. Тут я бы показывал какой-нибудь Toast с сообщением об ошибке.
https://github.com/delet-dis/visual-novel/blob/0a7792f344653943024f9c8a7464874669fd950b/app/src/main/java/com/delet_dis/vusialnovel/SceneActivity.kt#L101-L103

10. Конвертацию элемента из Json в класс можно было записать так вместо цикла. В цикле ты преобразуешь только один элемент, а тут массив. Но в скорости выигрыш будет минимальный, но понятнее будет в разы. Этот код можно еще улучшить. Советую подумать как. В целом всю работу с Json лучше вынести в отдельный класс.
```
val scenes: List<Scene> = Gson().fromJson(
    jsonArray.toString(),
    mutableListOf<Scene>()::class.java
)
```

11. Очистку значение в `SharedPreferences` стоит вынести из создания интента. Вот прям не место ей там.
https://github.com/delet-dis/visual-novel/blob/0a7792f344653943024f9c8a7464874669fd950b/app/src/main/java/com/delet_dis/vusialnovel/SceneActivity.kt#L71-L73

12 Если это делалось для того, чтобы не закрывалось активити, то лучше сделать так `override fun onBackPressed() = Unit`
https://github.com/delet-dis/visual-novel/blob/0a7792f344653943024f9c8a7464874669fd950b/app/src/main/java/com/delet_dis/vusialnovel/SceneActivity.kt#L90

**Comment by delet-dis** [comment]
1 . Не понимаю, речь идет про класс со статическими методами?
4 . Тут тоже не доходит, как фиксить. Пробовал через try catch, варнинг все равно видит, так же и с пятым пунктом
11 . Вынести в функцию?

**Comment by ShkiTTer** [comment]
1. Обычный класс, в котором будет содержаться вся работа с SharedPreferences. Без статичных методов. Ты просто будешь создавать экземпляр этого класса в активити. А можно его вообще сделать синглтоном, но это уже не обязательно.
2. Когда из интента достаешь данные там можно либо указать значение по умолчанию. Либо использовать оператор Элвис.
3. Сделать метод, например, clearPrefs и там уже очищать SharedPreferences

**Comment by delet-dis** [comment]
![image](https://user-images.githubusercontent.com/47276603/102990291-b36b1280-4549-11eb-8721-f68e946ce4f7.png)
![image](https://user-images.githubusercontent.com/47276603/102990314-ba922080-4549-11eb-814a-a4e75eea143b.png)
Теперь пытаюсь переехать на layoutInflater, все классно, но создаются обычные кнопки вместо materialButton, в чем может быть проблема?

**Comment by ShkiTTer** [comment]
Судя по коду создается именно MaterialButton. Ты уверен, что там просто Button?

Вот только что прогнал этот код и точно создает MaterialButton
```
val button = layoutInflater.inflate(R.layout.view_button, screenRoot, false) as MaterialButton
```
![image](https://user-images.githubusercontent.com/21283370/102991402-b2d37b80-454b-11eb-9ecd-130eb414c3a7.png)

**Comment by delet-dis** [comment]
Да, анимация нажатия и высота не от materialButton, раньше такая же проблема была, когда создавался просто Button

**Comment by ShkiTTer** [comment]
Уверен? Я сейчас проверил и у меня две идентичные кнопки. Что я просто в разметке прописал, что через inflate создал и добавил в лайаут.

У тебя в теме какой parent?

**Comment by delet-dis** [comment]
Theme.MaterialComponents.DayNight.NoActionBar, все как положено

**Comment by ShkiTTer** [comment]
Странно. В любом случае, если будет не такая анимация на кнопке ничего страшного

**Comment by delet-dis** [comment]
Ну и она отличается от тех, что используются в первых двух activity, причем достаточно сильно. Может, возможно как-то принудительно стили нацепить?

**Comment by ShkiTTer** [comment]
Можно вынести стиль кнопки в отдельный стиль. А в теме прописать, чтобы все кнопки были именного этого стиля в проекте. В теме нужно добавить такую строчку и в ней уже указать название стиля
```
<item name="materialButtonStyle">@style/Button</item>
```

**Comment by delet-dis** [comment]
Спасибо, попробую

**Comment by delet-dis** [comment]
Попробовал и так:
`<item name="materialButtonStyle">@style/Widget.MaterialComponents.Button</item>`
и так, сменив materialButton в самом шаблоне на простой Button:
`<item name="android:buttonStyle">@style/Widget.MaterialComponents.Button</item>`
и нацепил стиль прямо в разметке кнопки:
`style="@style/Widget.MaterialComponents.Button"`
Все три варианта не помогают, кнопка такая же толстая и нажимается без заливки

**Comment by ShkiTTer** [comment]
Странно. Особенно странно, что она сильно изменяется. 
Я завтра попробую в твоем проекте это сам сделать. Может так понятнее будет.

**Comment by delet-dis** [comment]
Буду ждать, спасибо

**Comment by delet-dis** [comment]
Проблема решена, Лидия посоветовала убрать background у кнопки, аргументируя это тем, что стили при изменении этого параметра "исчезают", это помогло.

**Comment by ShkiTTer** [comment]
А, да. Есть такой косяк.

**Comment by delet-dis** [comment]
Выношу работу с JSON в Singleton, заменяя парсинг в цикле на ваше решение. Наткнулся на ошибку преобразования. Как я понимаю, это решение
```
val scenes: List<Scene> = Gson().fromJson(
    jsonArray.toString(),
    mutableListOf<Scene>()::class.java
)
```
возвращает мапу<Object, Object>, что нельзя напрямую закастить в мой Scene.
Понял, как переводить простое сочетание ключ-значение в класс, но нет представления о том, как применить это с моей вложенностью в ArrayOfVariant, можете подсказать пожалуйста?

**Comment by ShkiTTer** [comment]
Это решение было написано в твоем проекте и оно работает. Для него никакой цикл не нужен. Вот по сути вся конвертация JSON'a в Scene
```
val jsonArray = JSONObject(loadJSONFromAsset(applicationContext)).getJSONArray("scenes")
    val scenes: List<Scene> = Gson().fromJson(
      jsonArray.toString(),
      mutableListOf<Scene>()::class.java
    )
```

**Comment by delet-dis** [comment]
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.delet_dis.visualnovel/com.delet_dis.visualnovel.SceneActivity}: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.delet_dis.visualnovel.Scene`
Я что-то не так делаю?

**Comment by ShkiTTer** [comment]
Покажи весь код считывания JSON и конвертации

**Comment by delet-dis** [comment]
https://github.com/delet-dis/visual-novel/blob/244fc3fb0c9a3129069dbd1f6ea942256cf42eb7/app/src/main/java/com/delet_dis/vusialnovel/JsonHelper.kt#L10-L35

**Comment by delet-dis** [comment]
Ой

**Comment by delet-dis** [comment]
```
object JsonHelper {

  fun parseJson(context: Context, filename: String): List<Scene> {
    val jsonArray = JSONObject(loadJSONFromAsset(context)?:"").getJSONArray("scenes")
    return Gson().fromJson(
      jsonArray.toString(),
      mutableListOf<Scene>()::class.java
    )
  }

  private fun loadJSONFromAsset(mContext: Context): String? {
    var json: String? = null
    try {
      val inputStream: InputStream = mContext.assets.open(Constants.scenesFilename)
      val size: Int = inputStream.available()
      val buffer = ByteArray(size)
      inputStream.read(buffer)
      inputStream.close()
      json = String(buffer, Charset.forName("UTF-8"))
    } catch (e: Exception) {
      Toast.makeText(mContext, "JSON parsing error", Toast.LENGTH_SHORT).show()
    }
    return json
  }

}
```

**Comment by delet-dis** [comment]
В return'е parseJson'а ошибка

**Comment by ShkiTTer** [comment]
Ты сам JSON не менял?
Я сейчас скопировал твой код и все работает. 
Кстати, какое значение лежит в Constants.scenesFilename?

**Comment by delet-dis** [comment]
Нет, не трогал
`const val scenesFilename = "Scenes.json"`

**Comment by ShkiTTer** [comment]
У тебя сейчас эти изменения залиты в гит, чтобы я скачал и попробовал запустить?

**Comment by delet-dis** [comment]
Да, ветки синхронизированы

**Comment by ShkiTTer** [comment]
Сейчас тогда попробую

**Comment by ShkiTTer** [comment]
Ты не поверишь, но все работает

**Comment by delet-dis** [comment]
Чистый клон?

**Comment by ShkiTTer** [comment]
Да, вот просто склонил репу

Попробуй сделать Build -> Clean Project. Затем запустить заново

**Comment by delet-dis** [comment]
У меня краш, сейчас на эмуляторе попробую

**Comment by delet-dis** [comment]
Нет, тоже краш. Если что, он возникает после ввода имени и переходе на следующее активити, не при открытии приложения

**Comment by ShkiTTer** [comment]
Погодь. Поймал твою ошибку. Он почему-то криво конвертит. Сейчас поколдую малость и отпишу

**Comment by delet-dis** [comment]
Спасибо, жду

**Comment by ShkiTTer** [comment]
Сделай вот так. Либа Gson что-то с List не дружит
```
return Gson().fromJson(
      jsonArray.toString(),
      Array<Scene>::class.java
    ).toList()
```

**Comment by delet-dis** [comment]
Спасибо за помощь, ожило

**Comment by delet-dis** [comment]
Все пункты закрыл. Жду дальнейших указаний

**Comment by ShkiTTer** [comment]
Хорошо. Я завтра пробегусь по коду

**Comment by ShkiTTer** [comment]
В целом все хорошо. Дам пару советов на будущее, тут уже можешь не поправлять.
1. Ты объявил JsonHelper, как Object из-за чего тебе пришлось в каждый метод отдельно передавать контекст. Лучше в данном случае было бы сделать его классом и передать контекст один раз в конструктор.
2. Когда у тебя получается длинное условие (хороший показатель оно все не помещается в одну строку) используй фигурные скобки для блоков if/else. Тогда все становится гораздо более читаемым
